### PR TITLE
initial skeleton

### PR DESCRIPTION
**Pull request by EvertRdrgz**

### CODE REVIEW

**Comment by EvertRdrgz** [comment]
Yes, that's the plan :)

**Comment by mattwebbio** [comment]
Are these managed per-ranch? I was under the assumption that it was global across all ranches

**Comment by EvertRdrgz** [comment]
Correct, it's global across all ranches and should only be available to admins

**Comment by mattwebbio** [comment]
This is only broken because I refactored the alert service, will be an easy fix

**Comment by mattwebbio** [comment]
I don't want to merge quite yet, because I want to figure out an actual plan with you and Will for how we should structure all these components (particularly because I think we'll need multiple for entry and possibly multiple for management)

**Pull request closed without merging**
