### PR TITLE
Final export service

### PR DESCRIPTION
**Pull request by NolanGuzman97**
Temporary pull to allow chandler to use export function

### CODE REVIEW

**Comment by mattwebbio** [comment]
Lint is NOT happy lol

**Comment by NolanGuzman97** [comment]
> Lint is NOT happy lol

Not even slightly lol, I'll syntax fix rn

**Comment by NolanGuzman97** [comment]
Lint continues to hate my guts

**Comment by mattwebbio** [comment]
> Lint continues to hate my guts

:(

**Comment by mattwebbio** [comment]
YAAY

**Pull request merged**
